site_name: Discovery
site_author: Michael Hubbard (@rikosintie)
site_description: A site dedicated to the Network Discovery project.
site_url: https://discovery.rikosintie.com
nav:
  - Home: README.md
  - Intro: intro.md
  - Getting Started: Getting_Started.md
  - Usage: usage.md
  - Helper Scripts: Helper-scripts.md
  - Security Policy: SECURITY.md

theme:
  font:
    text: Roboto
    code: Red Hat Mono
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate # (1)!
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate

  language: en
  favicon: img/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  icon:
    admonition:
      info: octicons/info-16
      note: octicons/tag-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      success: octicons/check-16
      question: octicons/question-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
    - social
    - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rikosintie
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rikosintie
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mwhubbard/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.mark


copyright: |
  &copy; 2025 <a href="https://github.com/rikosintie" target="_blank" rel="noopener">Michael Hubbard</a>
